name : "Run Postman collection"

on: 
    push:
        branches:
            - test1
jobs:
    run-collection-with-env: 
        permissions: 
            pull-requests: write 
        uses: Dyeto/my--reusable-github-actions-workflows/.github/workflows/run_postman_collections.yml@main
        with: 
            collection_id: 28219024-b9bcfb61-7ab2-46c7-bb64-9741e5460c7b
            postman_env_id: 28219024-fa3ed16a-5885-41ef-a309-e4926e8f7aa3
            jira_project_key: CIAM

        secrets:
            postman_api_key : ${{ secrets.POSTMAN_API_KEY }}
            jira_username: xxxx
            jira_password: xxxx

        
    run-collection-without-env: 
        permissions: 
            pull-requests: write 
        uses: Dyeto/my--reusable-github-actions-workflows/.github/workflows/run_postman_collections.yml@main
        with: 
            collection_id: 28219024-60010111-1f16-4d98-8ece-30f8d44934da
            jira_project_key: CIAM
        secrets:
            postman_api_key : ${{ secrets.POSTMAN_API_KEY }}
            jira_username: xxxx
            jira_password: xxxx

                


